### PR TITLE
Added HttpGelfClient

### PR DESCRIPTION
**Pull request by mersadk**
Added support for HTTP/HTTPS Graylog input endpoints.

### CODE REVIEW

**Comment by mattwcole** [comment]
Thanks @mersadk this is looking good. I'll have a closer look this week and see if I can get the CI build passing before we merge it.

**Comment by mattwcole** [comment]
I've pushed a branch with some minor changes to the implementation [here](https://github.com/mersadk/gelf-extensions-logging/compare/dev...mattwcole:mersadk-dev). If you are happy with these, you should be able to merge them into your PR. I'm not sure why the Travis build is failing, the tests pass locally, I'll have to investigate further.

**Comment by mersadk** [comment]
Looks great. I've merged branches.

**Comment by mattwcole** [comment]
OK I managed to get the build green simply by upgrading Graylog and Elasticsearch. If you merge that branch again, this PR *should* go green.

**Comment by mersadk** [comment]
Done but it appears that build again failed.

**Comment by mattwcole** [comment]
I'm going to merge so I don't have to keep sending you changes as I try to fix it. Thanks again for the contribution!

**Pull request merged**
