### PR TITLE
Add exceptionHandler

### PR DESCRIPTION
**Pull request by MightGainer**
Hi, @mattwcole!

I have experienced problems while sending udp messages to remote graylog host. And I spent a lot of time to detect problems. It would be really nice to have an opportunity to detect problems that occur during sending (for monitoring at first). I cannot imagine any workaround of that, so I want to introduce a possible solution for me.

Please, write back soon. Any comments are welcome!

Thanks a lot!

### CODE REVIEW

**Comment by mattwcole** [comment]
Hi, do you have some examples of exceptions that were being thrown in the `GelfMessageProcessor`, because there should never be any. `_messageBuffer.ReceiveAsync()` will throw an `InvalidOperationException` when `_messageBuffer.Complete()` is called during shutdown. Were you able to cause `_gelfClient.SendMessageAsync()` to throw?

**Comment by MightGainer** [comment]
Thanks a lot for quick answer!

Practically - I cannot say the example of errors. We've got problems with our .NET Framework app & binding redirects. The main hypothesis is that there are some runtime exceptions caused by incorrect redirects that we cannot see in our monitoring systems.

Fully case looks like that:
- app (framework) uses Gelf.Extensions.Logging
- app uses another lib with some packages (microsoft.extensions.logging) bumped to 5.0.0
- deploy with bump of another lib caused stop of gathering logs
- manually sent udp packages & ran sample app - both times logs were gathered successfully
- no errors seen in monitoring systems (app is working normally)
- graylog server, input, indices are working normally
- we checked sys calls & tried to capture udp packages on working machines and we did not see any udp packages sent

So, we are sure that messages are not sent. We suppose that there are some runtime errors that we cannot detect.

**Comment by mattwcole** [comment]
Although I wouldn't expect the UDP client to throw, I think it makes sense to be able to get error information out of the library, as currently there is no visibility. We may be able to take some inspiration from Serilog's [`SelfLog`](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics), rather than using an exception callback. This would allow us to replace all the `Debug.Fail()` calls, including those that aren't handling an exception.

I appreciate you are trying to debug an ongoing issue, you may want to create a custom NuGet package with your code changes (or add the modified Gelf.Extensions.Logging project to your solution) if you need something ASAP.

**Comment by MightGainer** [comment]
Thanks a lot for answering!

I mirrored the repository and pushed a custom NuGet package. Then I added exception handling and that is what I got

> [FileLoadException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]

Now we are going to use a mirror but it will be a great news for us if you add any workaround on this issue. Thanks a lot again!

P.S. I am going to close this PR.

P.P.S. If you would be so kind, I would be happy to help you to implement necessary features. So, keep in touch if needed!

**Comment by mattwcole** [comment]
I have just released a pre-release [v2.3.0-pre1](https://www.nuget.org/packages/Gelf.Extensions.Logging/2.3.0-pre1) with [these changes](https://github.com/mattwcole/gelf-extensions-logging/compare/trace-errors) that replace `Debug.Fail()` calls with `Trace.WriteError()`. You can now print any errors to the console by registering a [trace listener](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.trace?view=net-5.0).

```cshar
Trace.Listeners.Add(new ConsoleTraceListener());
```

It turns out that the UDP client does throw a `SocketException` if it fails to connect, it's possible you are getting a similar error.

```
Gelf.Extensions.Logging.Samples.AspNetCore3 Error: 0 : Unhandled exception while sending GELF message
System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.UdpClient.BeginSend(Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.UdpClient.<>c.<SendAsync>b__54_0(Byte[] targetDatagram, Int32 targetBytes, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1,TArg2](Func`5 beginMethod, Func`2 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Sockets.UdpClient.SendAsync(Byte[] datagram, Int32 bytes)
   at Gelf.Extensions.Logging.UdpGelfClient.SendMessageAsync(GelfMessage message)
   at Gelf.Extensions.Logging.GelfMessageProcessor.StartAsync()
```

**Pull request closed without merging**
