### PR TITLE
Add TCP Support (Updated)

### PR DESCRIPTION
**Pull request by devn1x**
Because there seems to be no update in sight regarding pull request #65, I hope its okay if I try to contribute the last finishing touches to this feature.

Solves #64

### CODE REVIEW

**Comment by mattwcole** [comment]
Fantastic, thanks for tidying up the feature. There is one more small tweak needed, but I don't have permission to modify your PR. I've [put it on the old one](https://github.com/mattwcole/gelf-extensions-logging/pull/65/commits/e658d13241aa630384e7ee7fc5bb5e36e39753f3), would you be able to include it here?

**Comment by devn1x** [comment]
Okay, I already included your modification and I added permission for you to modify my pr, if you have anything left to add.

Today or tomorrow I will look at the changes once again and if I don't find anything obviously wrong, I will put it up for review.

Also, just so you know and that it's documented somewhere: I did not implement the TCP timeout, because I couldn't get it to work in a clean and reliable way.

**Comment by mattwcole** [comment]
This is released in [v2.5.0-pre1](https://www.nuget.org/packages/Gelf.Extensions.Logging/2.5.0-pre1). I'll release a stable version in a few days unless you encounter any issues.

**Comment by devn1x** [comment]
Thank you so much. I'm going to start implementing this and will report and try to fix any issues that may arise.

**Pull request merged**
